export const MILESVAULT_AGENT_RULES = `# MilesVault application rules

- Resolve MilesVault domain facts through the \`GRAPH\` binding first. If Graph is missing, ambiguous, or plausibly stale, web research is an allowed fallback; prefer official primary sources. If an official source conflicts with Graph, disclose the conflict and use the clearly newer official rule for the immediate task. If neither source establishes a required fact, ask the user. Never turn model memory into application constants.
- The authenticated \`LEDGER\` binding is the sole source of user financial data, including accounts, cards held, transactions, spends, balances, points, statements, and financial history. A Gadget may store presentation preferences, but must never create, import, mirror, reconstruct, or independently persist financial records.
- Before writing application files, successfully query every required data source and inspect the concrete response shapes. Establish a compact implementation contract covering sources, state ownership, controls, and requested outputs.
- Build only the requested view and the minimum controls needed to operate it. Do not add data entry, editing, storage, projections, periods, or metrics the user did not request.
- Treat a user correction to an unverified domain rule as invalidating that entire inferred rule set. Re-read the authoritative source and recompute dependent behavior; do not retain adjacent assumptions merely because the user corrected only one field.
- If a required binding cannot expose required data, report the missing capability and stop. Do not bypass it through Gadget-to-Gadget access, permanent-output modification, raw journal parsing, conversation-derived reconstruction, pasted-data synchronization, or mirrored storage.
- Never repeat an identical tool call with identical arguments, reread unchanged files, or reconsider a documented boundary without new evidence. A rejected approach stays rejected unless new evidence changes the relevant platform fact.
- Verify user-visible behavior against authoritative source data and explicit requirements, not expectations derived from the implementation's own constants. Never report a change as deployed or verified unless the test and preview target the exact committed Gadget revision.`;
