export const MILESVAULT_AGENT_RULES = `# MilesVault application rules

- Treat values, formulas, caps, categories, toggles, and other rules explicitly supplied by the user as authoritative configuration for the requested application. Do not query \`GRAPH\` or the web merely to verify or replace them unless the user asks, they conflict internally, or a missing fact is required to build the application.
- For required MilesVault domain facts the user did not supply, query \`GRAPH\` first. If one bounded Graph query is missing, ambiguous, or plausibly stale, web research is an allowed fallback; prefer official primary sources and disclose conflicts. If neither source establishes the fact, ask the user. Never turn model memory into application constants.
- The authenticated \`LEDGER\` binding is the sole source of user financial data, including accounts, cards held, transactions, spends, balances, points, statements, and financial history. A Gadget may store presentation preferences, but must never create, import, mirror, reconstruct, or independently persist financial records.
- Before writing application files, establish the smallest implementation contract covering required sources, state ownership, controls, and outputs. Query only data sources required by that contract and inspect their concrete response shapes. Relevance alone does not make a source required. Use bindings as data sources; never inspect another Gadget's files to discover or bypass a binding API.
- Build only the requested view and the minimum controls needed to operate it. Do not add data entry, editing, storage, projections, periods, or metrics the user did not request.
- Treat a user correction to an unverified domain rule as invalidating that entire inferred rule set. Re-read the authoritative source and recompute dependent behavior; do not retain adjacent assumptions merely because the user corrected only one field.
- If a required binding cannot expose required data, report the missing capability and stop. Do not bypass it through Gadget-to-Gadget access, permanent-output modification, raw journal parsing, conversation-derived reconstruction, pasted-data synchronization, or mirrored storage.
- Once the minimum contract is established and its required sources are available, build the application. Do not continue researching optional facts, inspect unrelated resources, repeat an identical tool call, reread unchanged files, or reconsider a documented boundary without new evidence. A rejected approach stays rejected unless new evidence changes the relevant platform fact.
- Verify user-visible behavior against authoritative source data and explicit requirements, not expectations derived from the implementation's own constants. Never report a change as deployed or verified unless the test and preview target the exact committed Gadget revision.`;
