/** GENERATED by M/scripts/generate-os-doctor-contract.mjs; do not hand edit.
 * src/durable/doctor-do.ts sha256:942fc560eb0314b7cae1b5effba1377a9547e4b903c821785103ff41b6936d87
 * src/lib/os-budget.ts sha256:5da8246a177b5d7987dc0859fcf76d5eea1855fd676c3acfcdc8a242a4bf7245
 * src/lib/os-doctor-contract.ts sha256:92cf9fa36fc7d4c15d0dc5463d7f51ebb1fe9cbd4ff369603175ac47a62fb017
 * src/lib/os-doctor-control-contract.ts sha256:685be5a10e5274eeb5e25bb58fe77119b9e568e274714d5ee622ee6b32843632
 * src/lib/os-doctor-control.ts sha256:2db6f8a19f61af910ed42032bde71db1e3746a0a0206a8d7cf4b5d6989dd3f81
 * src/lib/os-doctor-projection.ts sha256:6c6d0603527cec248550d0f1ae0c261e3b4e1ee028a2c1f443990853c278729d
 * src/lib/os-doctor-scope.ts sha256:edebec8c098b4ce1c742b6bc2ac3459fc209cb717033bc737f9ead85064557ad
 * src/lib/os-doctor-source.ts sha256:ec7c0ecbfc97b8a2348effeb16251586fff9e0526ab0824b7a2e0babddc0d41e
 */
// BEGIN READ DECLARATIONS
/** Materialized Doctor reads only. No scan, dismissal, proposal or commit authority. */
export type DoctorReadRequest = {
    view: 'findings';
    status: 'open' | 'dismissed';
    after?: string;
} | {
    view: 'detail';
    id: string;
};
/** Evidence is returned verbatim or the request fails; it is never silently shortened. */
export type DoctorReadPage = {
    version: 1;
    source: 'canonical-doctor-materialized';
    lastScanAt: number | null;
    inFlight: boolean;
    /** Legacy scan timestamps do not establish registry coverage or successful completion. */
    coverage: 'unverified';
    /** Last native attempt; legacy timestamps remain unverified. Not current-health certification. */
    scan: DoctorScanManifest | null;
    findings: DoctorReadFinding[];
    evidence: string[] | null;
    next: string | null;
    limitations: string[];
};
export type DoctorScanManifest = {
    id: string;
    startedAt: number;
    finishedAt: number;
    status: 'complete' | 'partial' | 'failed';
    sourceVersion: string | null;
    coverage: Record<DoctorRule, 'complete' | 'skipped' | 'failed'>;
    reason: 'complete' | 'source-unavailable' | 'registry-unavailable' | 'changed-or-revoked' | 'finding-unavailable' | 'metadata-unavailable';
    /** Snapshot only, never a claim that the current journal is healthy. */
    consistency: 'bounded-ledger-snapshot-live-registry';
};
export type DoctorRule = typeof DOCTOR_RULES[number];
/** Shared read-only scan metadata; private control capabilities are defined separately. */
export declare const DOCTOR_RULES: readonly [
    "negative-pending",
    "non-canonical-root",
    "unknown-card",
    "card-shape",
    "card-number-missing",
    "currency-owned-pool",
    "unknown-pool",
    "duplicate-open"
];
/** Canonical finding metadata. The fingerprint is not an approval or revision token. */
export type DoctorReadFinding = {
    id: string;
    /** Opaque OCC revision, invalidated by every evidence/status change; not approval authority. */
    revision: string;
    rule: string;
    severity: 'attention' | 'tidy';
    title: string;
    detail: string;
    account: string | null;
    status: 'open' | 'dismissed' | 'resolved';
    foundAt: number;
};
/** Actual canonical READ signature; no control authority. */
export type DoctorCanonicalReadApi = { os_doctor_read: (input: DoctorReadRequest) => Promise<DoctorReadPage> };
// END READ DECLARATIONS
/** PRIVATE binding contract. Runtime shape checks are not cryptographic authentication.
 * Only deployment code may supply this root-derived, owner-bound facet. Never mint from
 * a browser runId/key, expose to agents, finish the root here, or silently start a new run.
 */
export interface DoctorUsageFacet {
    getOwner(): Promise<{
        canonicalKey: string;
    }>;
    getGrant(): Promise<OsRunGrant>;
    reserve(usage: OsUsageRequest): Promise<string>;
}
export type OsRunGrant = {
    allowed: true;
    runId: string;
    expiresAt: number;
} | Extract<OsBudgetResult, {
    allowed: false;
}>;
export type OsBudgetResult = {
    allowed: true;
} | {
    allowed: false;
    reason: 'daily_limit' | 'run_limit' | 'expired_run' | 'concurrent_runs' | 'unavailable';
    resource?: OsResource;
};
export type OsResource = (typeof OS_RESOURCE_KEYS)[number];
/** Resource dimensions charged only to the OS beta, independently of monitoring rollups. */
export declare const OS_RESOURCE_KEYS: readonly [
    "modelRequests",
    "tokens",
    "capabilityCalls",
    "externalRequests",
    "pendingWrites",
    "scheduledStarts"
];
export type OsUsageRequest = Partial<OsUsage>;
export type OsUsage = Record<OsResource, number>;
export type DoctorRecheckResult = {
    status: 'busy';
} | {
    status: 'finished';
    manifest: DoctorScanManifest;
};
export type DoctorDismissRequest = {
    id: string;
    revision: string;
};
/** Separate human-only metadata authority. Not a journal approval or agent observation. */
export interface DoctorDismissAuthority extends DoctorUsageFacet {
    authorizeDismiss(input: DoctorDismissRequest): Promise<void>;
}
export type DoctorDismissResult = {
    status: 'dismissed' | 'already-dismissed' | 'missing' | 'stale' | 'busy';
    revision?: string;
};
/** PRIVATE service signatures. Never expose these facets to a browser, agent or sandbox. */
export type DoctorCanonicalControlApi = { os_doctor_recheck: (facet: DoctorUsageFacet) => Promise<DoctorRecheckResult>; os_doctor_dismiss: (input: DoctorDismissRequest, authority: DoctorDismissAuthority) => Promise<DoctorDismissResult> };
