/** GENERATED by M/scripts/generate-os-doctor-contract.mjs; do not hand edit.
 * src/lib/os-doctor-contract.ts sha256:008cd7058ed8dd3f9069d4e7e4a762ba3dab8f0109c48c8345a4d2d2d3e73bb8
 * src/lib/os-doctor-projection.ts sha256:82e8d7ffe33cf55f7a34fd51c34be8696223d09e32141e06d2b510ca5d14b514
 * src/durable/doctor-do.ts sha256:ac733a1178c1aed90de56ee0b5a2537da0685ec34f9f24bd14953b50dfff4cbd
 */
/** Materialized Doctor reads only. No scan, dismissal, proposal or commit authority. */
export type DoctorReadRequest = {
    view: 'findings';
    status: 'open' | 'dismissed';
    after?: string;
} | {
    view: 'detail';
    id: string;
};
/** Canonical finding metadata. The fingerprint is not an approval or revision token. */
export type DoctorReadFinding = {
    id: string;
    rule: string;
    severity: 'attention' | 'tidy';
    title: string;
    detail: string;
    account: string | null;
    status: 'open' | 'dismissed' | 'resolved';
    foundAt: number;
};
/** Evidence is returned verbatim or the request fails; it is never silently shortened. */
export type DoctorReadPage = {
    version: 1;
    source: 'canonical-doctor-materialized';
    lastScanAt: number | null;
    inFlight: boolean;
    /** Legacy scan timestamps do not establish registry coverage or successful completion. */
    coverage: 'unverified';
    findings: DoctorReadFinding[];
    evidence: string[] | null;
    next: string | null;
    limitations: string[];
};
/** No user keys, arbitrary SQL, page-size controls or mutation selectors are accepted. */
export declare function validateDoctorReadRequest(value: unknown): asserts value is DoctorReadRequest;

/** Derived from the actual canonical DoctorDO method by the TypeScript checker. Read authority only. */
export type DoctorCanonicalReadApi = { os_doctor_read: (input: DoctorReadRequest) => Promise<DoctorReadPage> };
