/** GENERATED by M/scripts/generate-os-doctor-contract.mjs; do not hand edit.
 * src/lib/os-doctor-contract.ts sha256:92cf9fa36fc7d4c15d0dc5463d7f51ebb1fe9cbd4ff369603175ac47a62fb017
 * src/lib/os-doctor-projection.ts sha256:6c6d0603527cec248550d0f1ae0c261e3b4e1ee028a2c1f443990853c278729d
 * src/durable/doctor-do.ts sha256:942fc560eb0314b7cae1b5effba1377a9547e4b903c821785103ff41b6936d87
 */
/** Shared read-only scan metadata; private control capabilities are defined separately. */
export declare const DOCTOR_RULES: readonly ["negative-pending", "non-canonical-root", "unknown-card", "card-shape", "card-number-missing", "currency-owned-pool", "unknown-pool", "duplicate-open"];
export type DoctorRule = typeof DOCTOR_RULES[number];
export type DoctorScanManifest = {
    id: string;
    startedAt: number;
    finishedAt: number;
    status: 'complete' | 'partial' | 'failed';
    sourceVersion: string | null;
    coverage: Record<DoctorRule, 'complete' | 'skipped' | 'failed'>;
    reason: 'complete' | 'source-unavailable' | 'registry-unavailable' | 'changed-or-revoked' | 'finding-unavailable' | 'metadata-unavailable';
    /** Snapshot only, never a claim that the current journal is healthy. */
    consistency: 'bounded-ledger-snapshot-live-registry';
};
/** Materialized Doctor reads only. No scan, dismissal, proposal or commit authority. */
export type DoctorReadRequest = {
    view: 'findings';
    status: 'open' | 'dismissed';
    after?: string;
} | {
    view: 'detail';
    id: string;
};
/** Canonical finding metadata. The fingerprint is not an approval or revision token. */
export type DoctorReadFinding = {
    id: string;
    /** Opaque OCC revision, invalidated by every evidence/status change; not approval authority. */
    revision: string;
    rule: string;
    severity: 'attention' | 'tidy';
    title: string;
    detail: string;
    account: string | null;
    status: 'open' | 'dismissed' | 'resolved';
    foundAt: number;
};
/** Evidence is returned verbatim or the request fails; it is never silently shortened. */
export type DoctorReadPage = {
    version: 1;
    source: 'canonical-doctor-materialized';
    lastScanAt: number | null;
    inFlight: boolean;
    /** Legacy scan timestamps do not establish registry coverage or successful completion. */
    coverage: 'unverified';
    /** Last native attempt; legacy timestamps remain unverified. Not current-health certification. */
    scan: DoctorScanManifest | null;
    findings: DoctorReadFinding[];
    evidence: string[] | null;
    next: string | null;
    limitations: string[];
};
/** No user keys, arbitrary SQL, page-size controls or mutation selectors are accepted. */
export declare function validateDoctorReadRequest(value: unknown): asserts value is DoctorReadRequest;

/** Derived from the actual canonical DoctorDO method by the TypeScript checker. Read authority only. */
export type DoctorCanonicalReadApi = { os_doctor_read: (input: DoctorReadRequest) => Promise<DoctorReadPage> };
