/** GENERATED by M/scripts/generate-os-usage-contract.mjs; do not edit.
 * src/lib/os-budget.ts sha256:5da8246a177b5d7987dc0859fcf76d5eea1855fd676c3acfcdc8a242a4bf7245
 * src/lib/os-usage-acquisition-v2.ts sha256:0936db31f061540181703073cca49dd7f6bcd80084200456d5816b897147fb7e
 * src/workers/os-usage-policy.ts sha256:618a320b0085ef0e92cb5ca83759902d83e69efa1117798ba32277d5cd79c4f5
 */
import type {WorkerEntrypoint} from 'cloudflare:workers';
/** Canonical private DTO from src/lib/os-budget.ts. */
/** Resource dimensions charged only to the OS beta, independently of monitoring rollups. */
export declare const OS_RESOURCE_KEYS: readonly [
    "modelRequests",
    "tokens",
    "capabilityCalls",
    "externalRequests",
    "pendingWrites",
    "scheduledStarts"
];
/** Canonical private DTO from src/lib/os-budget.ts. */
export type OsResource = (typeof OS_RESOURCE_KEYS)[number];
/** Canonical private DTO from src/lib/os-budget.ts. */
export type OsUsage = Record<OsResource, number>;
/** Canonical private DTO from src/lib/os-budget.ts. */
export type OsUsageRequest = Partial<OsUsage>;
/** Canonical private DTO from src/lib/os-budget.ts. */
export type OsBudgetConfig = {
    daily: OsUsage;
    run: OsUsage;
    runDurationMs: number;
    concurrentRuns: number;
};
/** Canonical private DTO from src/lib/os-budget.ts. */
export type OsBudgetResult = {
    allowed: true;
} | {
    allowed: false;
    reason: 'daily_limit' | 'run_limit' | 'expired_run' | 'concurrent_runs' | 'unavailable';
    resource?: OsResource;
};
/** Canonical private DTO from src/lib/os-budget.ts. */
export type OsRunGrant = {
    allowed: true;
    runId: string;
    expiresAt: number;
} | Extract<OsBudgetResult, {
    allowed: false;
}>;
/** Canonical private DTO from src/lib/os-budget.ts. */
/** Existing operator concurrency ceiling; also bounds private durable acquisition slots. */
export declare const OS_MAX_CONCURRENT_RUNS = 20;
/** Canonical private DTO from src/lib/os-usage-acquisition-v2.ts. */
/** Private host protocol only. Account selection/authentication belongs to the trusted binding. */
export declare const OS_ACQUISITION_SLOT_COUNT = 20;
/** Canonical private DTO from src/lib/os-usage-acquisition-v2.ts. */
/** Exact signed SQLite integer ceiling; never convert generations through Number. */
export declare const OS_ACQUISITION_MAX_GENERATION = "9223372036854775807";
/** Canonical private DTO from src/lib/os-usage-acquisition-v2.ts. */
/** Fixed, original workflow deadline; no stage may start a fresh window. */
export declare const OS_ACQUISITION_WINDOW_MS = 5000;
/** Canonical private DTO from src/lib/os-usage-acquisition-v2.ts. */
/** Persist the entire ticket at the caller before sending any mutating RPC. */
export type OsAcquisitionTicketV2 = {
    protocol: 2;
    namespace: string;
    slot: number;
    generation: string;
    ownerId: string;
    operationId: string;
    payloadHash: string;
    runId: string;
    issuedAt: number;
    acquireBy: number;
};
/** Canonical private DTO from src/lib/os-usage-acquisition-v2.ts. */
/** Discovery grants no authority. Namespace is a persisted per-account authority epoch. */
export type OsAcquisitionProtocolV2 = {
    protocol: 2;
    namespace: string;
    slotCount: 20;
    features: readonly [
        'pending-activation',
        'durable-fence',
        'fixed-expiry'
    ];
};
/** Canonical private DTO from src/lib/os-usage-acquisition-v2.ts. */
/** Pending/status records are recovery data, never dispatch permission. */
export type OsAcquisitionResultV2 = {
    protocol: 2;
    state: 'pending' | 'active';
    runId: string;
    expiresAt: number;
} | {
    protocol: 2;
    state: 'free' | 'terminal' | 'conflict' | 'invalid' | 'expired' | 'denied';
    reason?: Extract<OsBudgetResult, {
        allowed: false;
    }>['reason'];
};
/** Canonical private DTO from src/lib/os-usage-acquisition-v2.ts. */
/** Bounded, payload-free snapshot; use exact status to inspect only your own ticket. */
export type OsAcquisitionSnapshotV2 = OsAcquisitionProtocolV2 & {
    slots: {
        slot: number;
        generation: string;
        state: 'free' | 'pending' | 'active' | 'sealed';
    }[];
};
/** Private canonical service. Not a browser/agent capability; V2 never falls back to V1. */
export interface OsUsagePolicyApi extends WorkerEntrypoint {
  /** Actual OsUsagePolicy.getAcquisitionProtocolV2 signature. */
  getAcquisitionProtocolV2(storageKey: string): Promise<Omit<OsAcquisitionProtocolV2, "features"> & { features: readonly OsAcquisitionProtocolV2["features"][number][]; }>;
  /** Actual OsUsagePolicy.readAcquisitionSlotsV2 signature. */
  readAcquisitionSlotsV2(storageKey: string): Promise<Omit<OsAcquisitionSnapshotV2, "features"> & { features: readonly OsAcquisitionProtocolV2["features"][number][]; }>;
  /** Actual OsUsagePolicy.beginAcquisitionV2 signature. */
  beginAcquisitionV2(storageKey: string, ticket: OsAcquisitionTicketV2): Promise<OsAcquisitionResultV2>;
  /** Actual OsUsagePolicy.activateAcquisitionV2 signature. */
  activateAcquisitionV2(storageKey: string, ticket: OsAcquisitionTicketV2): Promise<OsAcquisitionResultV2>;
  /** Actual OsUsagePolicy.cancelAcquisitionV2 signature. */
  cancelAcquisitionV2(storageKey: string, ticket: OsAcquisitionTicketV2): Promise<OsAcquisitionResultV2>;
  /** Actual OsUsagePolicy.getAcquisitionStatusV2 signature. */
  getAcquisitionStatusV2(storageKey: string, ticket: OsAcquisitionTicketV2): Promise<OsAcquisitionResultV2>;
  /** Actual OsUsagePolicy.sweepAcquisitionsV2 signature. */
  sweepAcquisitionsV2(storageKey: string): Promise<void>;
  /** Actual OsUsagePolicy.beginRun signature. */
  beginRun(storageKey: string, runId: string): Promise<OsRunGrant>;
  /** Actual OsUsagePolicy.getRunGrant signature. */
  getRunGrant(storageKey: string, runId: string): Promise<OsRunGrant>;
  /** Actual OsUsagePolicy.reserve signature. */
  reserve(storageKey: string, runId: string, requestId: string, usage: OsUsageRequest): Promise<OsBudgetResult>;
  /** Actual OsUsagePolicy.settleTokens signature. */
  settleTokens(storageKey: string, requestId: string, tokens: number): Promise<void>;
  /** Actual OsUsagePolicy.finishRun signature. */
  finishRun(storageKey: string, runId: string): Promise<void>;
}
