/** GENERATED by M/scripts/generate-os-vault-contract.mjs; do not hand edit.
 * src/lib/os-vault-contract.ts sha256:30b0c41edbfd4ab83fb5f9f7e409f47de68b3e1e2c13e17180ab54fc48b97e62
 * src/lib/os-vault-projection.ts sha256:2023748d4dae7357e28c38682ec0d949ea25fdb84930c18e8b0b7e859197b23a
 * src/durable/ledger-do.ts sha256:4c2e5f896b714ef2d5bf31a9cb8c3a01d8ad11954415e01d1730fbee635a897e
 */
/** Canonical native Vault v1. Display projections, never settlement amounts or write authority. */
export declare const OS_VAULT_VERSION: 1;
/** Today-ending ranges only; current balances include future postings and assertion plugs. */
export type VaultRange = '1m' | '3m' | 'ytd' | '12m';
/** No identity, SQL, historical end date, or caller-controlled page size crosses this boundary. */
export type VaultRequest = {
    range: VaultRange;
    account?: string;
    currency?: string;
    after?: string;
    before?: {
        date: number;
        txn: number;
        idx: number;
    };
};
/** One account/commodity row; pending rewards stay separate from posted balance. */
export type VaultAccount = {
    account: string;
    currency: string;
    balance: string;
    pending: string;
    owed: number;
    state: 'owed' | 'credit' | 'settled' | 'balance';
};
/** Bounded posting evidence, not journal text. Amount retains canonical integer scale. */
export type VaultActivity = {
    date: number;
    txn: number;
    idx: number;
    account: string;
    currency: string;
    amountScaled: number;
    scale: number;
    payee: string;
    narration: string;
    textTruncated: boolean;
};
/** One read response, shared by dashboard and detail. Pagination is live, not a snapshot. */
export type VaultPage = {
    version: 1;
    period: {
        from: number;
        to: number;
    };
    accounts: VaultAccount[];
    nextAccount: string | null;
    pendingCaptures: {
        count: number;
        atLeast: boolean;
    };
    expenses: {
        account: string;
        currency: string;
        total: number;
        recordedFee: boolean;
    }[];
    expensesPartial: boolean;
    /** Canonical rolling 90-day negative card postings, NOT net expense-backed spend. */
    cardCharges90d: {
        account: string;
        currency: string;
        total: number;
    }[];
    chargesPartial: boolean;
    detail: null | {
        account: string;
        currency: string | null;
        currencies: string[];
        current: number;
        inflow: number;
        outflow: number;
        transactionCount: number;
        series: {
            date: number;
            balance: number;
        }[];
    };
    activity: VaultActivity[];
    nextActivity: VaultRequest['before'] | null;
    limitations: string[];
};
/** Exhausted-credit-safe SQL-only read; resource quotas and admission still apply. No financial integration. */
export declare const OS_VAULT_READ_CLASS: "canonical-bounded-read";
/** Strict boundary validation; unknown properties must not become authority selectors. */
export declare function validateVaultRequest(value: unknown): asserts value is VaultRequest;

/** Derived from the actual canonical LedgerDO method by the TypeScript checker. */
export type VaultCanonicalApi = { os_vault_page: (input: VaultRequest) => Promise<VaultPage> };
